#!/bin/bash
#config
#Configuration section

#interfaces configuration

mgmtif="eth1+eth2"
publicif="eth1+eth2"
privateif="eth1+eth2"
storageif="eth1+eth2"

mgmtbondmode="active-backup"
publicbondmode="active-backup"
privatebondmode="active-backup"
storagebondmode="active-backup"

#env configuration
env_id=1
role=compute

#Additional files
ASTUTE_YAML="/etc/fuel/astute.yaml"
NTA="config/nodes_to_add"
CHECK_RETRIES=180

#Binaries
JQ="config/jq"
GSC="$PYT /usr/bin/get_service_credentials.py"
GIT="/usr/bin/git"
SSH="/usr/bin/ssh"
SCP="/usr/bin/scp"
PYT="/usr/bin/python"
YUM="/usr/bin/yum -y"
RM="/bin/rm -rf"
MV="/bin/mv"
SCR="/usr/bin/screen"
MAKE="/usr/bin/make"
AWK="/usr/bin/awk"
GREP="/bin/grep"
HEAD="/usr/bin/head"
MKDIR="/bin/mkdir -p"
CP="/bin/cp -R"
SCTL="/usr/bin/supervisorctl"
FUEL="/usr/bin/fuel"
KILLALL="/usr/bin/killall"
CURL="/usr/bin/curl"

#Colors an appearence
RED="echo -en \\033[1;31m"
GREEN="echo -en \\033[1;32m"
RESET="echo -en \\033[0;39m"
YELLOW="echo -en \\e[0;93m"
BOLD=$(tput bold)
export COLUMNS=$(tput cols)
TOEND=$(tput hpa ${COLUMNS})$(tput cub 6)

#declare -a data=(`$FUEL node 2>/dev/null 2>&1 | grep -v ready | grep -v provisioned | grep None | grep -v deploying | grep -v "("  | grep -v ")"  | grep -v "Untitled" | grep "discover" | awk '{print $1,$5,$9,$11,$15}'`)

declare -a data=(`cat $NTA | grep -v ^#`)
data_count=${#data[*]}
let "nodes_count = $data_count / 2"  #cat nodes_to_add | grep -v ^# | wc -l

